### ISSUE TITLE
update profile registration description

### ISSUE THREAD

**Issue by andreasnef** [mets/METS-board#37]
http://www.loc.gov/standards/mets/profile_docs/submission.html

**Comment by karinbredenberg** [comment]
Have been in contact with LC and mail is updated.

**Comment by andreasnef** [comment]
Ok to close it, then? Mail addresses mentioned on this page are:
metsprofile@listserv.loc.gov
mets@listserv.loc.gov

**Comment by karinbredenberg** [comment]
Cant close since attachment don't pass the list server....

**Comment by aelkiss** [comment]
We will suggest that people send a link to new profiles rather than attaching them. The current page doesn't tell people to submit them as attachments, but doesn't tell them not to either. That should avoid the problem with attachments and avoid needing to list a personal email address on the submission page.
